### ISSUE TITLE
Clarify license for TSC description

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/governance#19]
I believe https://github.com/opendatakit/governance/blob/master/TECHNICAL-STEERING-COMMITTEE.md was derived from https://nodejs.org/en/about/governance/. 

As I understand it, that document is licensed under https://github.com/nodejs/nodejs.org/blob/master/LICENSE and so the license needs to live alongside our fork. I also think it's important to cite the source for institutional memory purposes. I would link to https://github.com/nodejs/nodejs.org/blob/09d663cfd4c61eb5ac343033af460af19bcf6aec/locale/en/about/governance.md in case there are future changes to it.

**Comment by yanokwa** [comment]
In an email I sent to the PMC in late September, 2017, I noted that the governance that we took from Node.js didn't have a license. I then checked their repo at https://github.com/nodejs/nodejs.org/ and reported: "Crisis averted. Their whole website is MIT licensed, so we are OK."

I've taken a screenshot (see below) to confirm that yes, their repo is MIT licensed and the text of the https://github.com/nodejs/nodejs.org/blob/master/LICENSE does confirm that as well.

<img width="998" alt="screen shot 2018-08-26 at 20 24 31" src="https://user-images.githubusercontent.com/32369/44638935-121a2480-a96e-11e8-8eea-c02a13ed3593.png">

I think the action is that we should is to add attribution to the documents we've used from Node.js. That is a mistake on my part and I'll be sending in a PR shortly.
