### ISSUE TITLE
Update TSC names in governance/TECHNICAL-STEERING-COMMITTEE.md

### ISSUE THREAD

**Issue by maprehensive** [opendatakit/governance#33]
References in this document to "ODK 1 TSC" should be replaced with "ODK TSC", and references to "ODK 2 TSC" with "ODK-X TSC".

**Comment by wbrunette** [comment]
Per the naming thread:
"The TSCs will keep their current names TSC 1 and TSC 2 temporarily. Waylon will lead a brainstorming process to see if we can come up with better names than that."
